name: CI Pipeline

on:
  pull_request:
    branches:
    - main
    paths:
    # Trigger only when there are changes to any code (as opposed to READMEs etc)
    - 'automation/**'
    - 'azure/**'
    - 'azure-pipeline-config/**'
    - '!automation/README.md'
    - '!azure/README.md'
    - '!azure-pipeline-config/README.md'
    # - '.codecov.yml'

jobs:
  build_and_test:
    strategy:
      matrix:
        dir: [ automation, azure, azure-pipeline-config ]
    runs-on: ubuntu-latest
    name: Build and test ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - id: build
        name: Build and test ${{ matrix.dir }}
        shell: bash
        run: |
          set -e

          cd ${{ matrix.dir }}
          npm ci
          npm run build

          # We must invoke tests via Docker, as the tests are using Pulumi executables
          cat ../Dockerfile | docker build --tag this_node -
          function npm()
          {
            docker run \
              --rm \
              -v "$(pwd)/:/code/:rw" \
              --entrypoint npm \
              -w /code \
              this_node \
              "$@"
          }
          npm run test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.dir }}
          directory: ${{ matrix.dir }}